name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for filing a bug report!**
  - type: checkboxes
    attributes:
      label: Verification
      options:
      - label: I searched existing issues for similar bug reports.
        required: true
  - type: input
    id: desc-brief
    attributes:
      label: What happened?
      description: A one-line description of the bug.
    validations:
      required: true
  - type: input
    id: desc-expected
    attributes:
      label: What should happen instead?
      description: The behaviour you were expecting to see.
  - type: textarea
    id: desc-steps
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
    validations:
      required: true
  - type: textarea
    id: desc-long
    attributes:
      label: More details?
      description: Give us more details about the bug and any personal attempts you made to fix it.
      placeholder: Tell us more!