name: Feature Request
description: File a feature request
labels: ["feature request"]
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for taking the time to fill out this feature request!**
  - type: checkboxes
    attributes:
      label: Verification
      options:
      - label: I searched existing issues for similar feature request.
        required: true
  - type: input
    id: desc-brief
    attributes:
      label: Pitch us your idea!
      description: A one-line elevator pitch of the feature you'd like to see implemented.
    validations:
      required: true
  - type: textarea
    id: desc-long
    attributes:
      label: Description
      description: |
        Give us a detailed description of the feature you are proposing.
        Tell us why this functionality should be included.